### ISSUE TITLE
Malformed rate line

### ISSUE THREAD

**Issue by Oguz-Guzel** [FlorianBury/BambooDatacardProducer#1]
I received `Malformed rate line` error while running combine with a datacard produced from `produceDataCards.py` script.

It was due to the lack of space between the 3rd and 4th entry of the rate line:
  
`rate                            65.9106238640   178.3664787843  25751.89976989533618034.7980126594`

How can I solve this? 
By the way, thank you very much for this great repository!

**Comment by FlorianBury** [comment]
Hi !

I did not expect this repository to have much impact but glad to see it can help some people.

This [commit](https://stackoverflow.com/questions/2189800/how-to-find-length-of-digits-in-an-integer) should hopefully fix the issue, let me know if you still encounter it.

**Comment by Oguz-Guzel** [comment]
Hi,

It's working very well now. Thanks!
